MessageExchangerParams:
  root: "./"
  history_size: 30

  folders_params:
    - folder: fold_1
      history_size: 3

    - folder: fold_2
      history_size: 5

    - folder: fold_3
      history_size: 4
